-- ============================================
-- 乔治·索罗斯名言
-- ============================================

INSERT OR IGNORE INTO quotes (id, content_cn, content_en, master_id, source, source_year, is_featured) VALUES
('eq-s001', '我有幸在正确的时候出现在正确的地方，这让我赚了很多钱。', 'I was lucky to be in the right place at the right time, which allowed me to make a lot of money.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s002', '当你对一笔交易有疑虑时，那往往是最危险的交易。', 'When you have doubts about a trade, that is often the most dangerous trade.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s003', '我不认为自己是一个投资者，我是一个试图发现市场错误定价的人。', 'I do not think of myself as an investor; I am someone trying to discover market mispricing.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s004', '在交易中，最重要的是知道什么时候退出。', 'In trading, the most important thing is knowing when to exit.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s005', '我的成功来自于对错误的快速承认和纠正。', 'My success comes from quickly acknowledging and correcting mistakes.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s006', '市场总是错误的，因为参与者的认知是有偏见的。', 'Markets are always wrong because participants perceptions are biased.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s007', '趋势是你的朋友，除非趋势反转。', 'The trend is your friend until the trend reverses.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s008', '我寻找的是极端的失衡，而不是小幅的偏差。', 'I look for extreme disequilibrium, not small deviations.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s009', '最好的交易往往是那些让你感到不舒服的交易。', 'The best trades are often those that make you feel uncomfortable.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s010', '当你发现趋势正在形成时，不要过早地逆势而行。', 'When you find a trend forming, do not be too early to go against it.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s011', '最重要的是不要赔钱，其次是记住第一条。', 'The most important thing is not to lose money; remember the first rule.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s012', '我从不固守任何一笔交易，如果市场证明我错了，我会立即退出。', 'I never cling to any trade; if the market proves me wrong, I exit immediately.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s013', '如果你交易得太多，你肯定会犯错。', 'If you trade too much, you are sure to make mistakes.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s014', '在金融市场上，最重要的不是预测，而是适应。', 'In financial markets, the most important thing is not prediction, but adaptation.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s015', '我的投资哲学基于一个简单的观点：人们对现实的看法总是有偏差的。', 'My investment philosophy is based on a simple idea: peoples perceptions of reality are always biased.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s016', '如果你发现自己处于一个无法退出的位置，那就是你投入太多的信号。', 'If you find yourself in a position you cannot exit, that is a signal you are too invested.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s017', '成功的人不是没有失败，而是能够从失败中快速恢复。', 'Successful people are not those without failures, but those who recover quickly from failures.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s018', '金融市场是非理性的，这种非理性是可以预测的。', 'Financial markets are irrational, and this irrationality is predictable.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s019', '不要试图战胜市场，要学会利用市场的错误。', 'Do not try to beat the market; learn to exploit market mistakes.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s020', '趋势反转的信号是当所有人都站在同一边时。', 'The signal of a trend reversal is when everyone is on the same side.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s021', '我在市场上生存的秘诀是知道自己什么时候是错的。', 'The secret to my survival in the market is knowing when I am wrong.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s022', '金融市场的历史是一部谎言和假象的历史。', 'The history of financial markets is a history of lies and falsehoods.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s023', '在市场上，最危险的事情是自满。', 'In the market, the most dangerous thing is complacency.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s024', '我不关心我对市场的看法，我只关心市场对事件的反应。', 'I do not care about my view of the market; I only care about how the market reacts to events.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s025', '成功的交易需要耐心、勇气和资金管理。', 'Successful trading requires patience, courage, and money management.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s026', '如果你发现自己在重复同样的错误，那是你需要改变的时候了。', 'If you find yourself repeating the same mistakes, it is time for you to change.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s027', '在市场上，钱是从恐慌者手中转移到自信者手中的。', 'In the market, money transfers from panickers to the confident.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s028', '我不寻找确定性，我寻找机会。', 'I do not look for certainty; I look for opportunities.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s029', '趋势开始时很温和，结束时很剧烈。', 'Trends start gentle and end violently.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s030', '最重要的事情是知道什么时候止损。', 'The most important thing is knowing when to stop losses.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s031', '金融市场是一个巨大的实验室，测试你的理论。', 'Financial markets are a huge laboratory testing your theories.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s032', '我寻找的是那些被严重错误定价的资产。', 'I look for assets that are severely mispriced.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s033', '不要和市场作对，要学会顺势而为。', 'Do not fight the market; learn to go with the flow.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s034', '成功的关键是风险管理，而不是预测。', 'The key to success is risk management, not prediction.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s035', '当我交易时，我总是假设我是错的。', 'When I trade, I always assume I am wrong.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s036', '市场的极端行为往往孕育着反转的机会。', 'Extreme market behavior often breeds opportunities for reversal.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s037', '我不在乎别人怎么看我，我只在乎我怎么看市场。', 'I do not care what others think of me; I only care about how I see the market.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s038', '交易的艺术在于知道什么时候加仓，什么时候减仓。', 'The art of trading is knowing when to add to positions and when to reduce them.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s039', '如果你发现自己在市场上追涨杀跌，那是你亏钱的捷径。', 'If you find yourself chasing rises and cutting losses in the market, that is a shortcut to losing money.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s040', '市场永远不会直线上升或下降，它总是曲折前进。', 'The market never rises or falls in a straight line; it always moves zigzag.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s041', '最重要的是保持灵活性，随时准备改变观点。', 'The most important thing is to stay flexible and be ready to change your views.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s042', '我从不根据预感做交易，我根据市场信号做交易。', 'I never trade on hunches; I trade on market signals.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s043', '在市场上，最大的错误是坚持错误。', 'In the market, the biggest mistake is persisting in errors.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s044', '市场的记忆是短暂的，这创造了重复的机会。', 'The markets memory is short, which creates repeated opportunities.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s045', '成功的交易者不是那些预测最准确的人，而是那些风险管理最好的人。', 'Successful traders are not those who predict most accurately, but those who manage risk best.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s046', '金融市场是一个复杂的自适应系统。', 'Financial markets are complex adaptive systems.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s047', '我寻找的是那些有自我强化趋势的市场。', 'I look for markets that have self-reinforcing trends.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s048', '在市场上，最重要的不是你对了多少次，而是你对的时候赚了多少。', 'In the market, the most important thing is not how many times you are right, but how much you make when you are right.', 'm-soros', '金融炼金术', 1987, 0),
('eq-s049', '市场先生的情绪可以在短期内推动价格远离价值。', 'Mr. Markets emotions can push prices far from value in the short term.', 'm-soros', '索罗斯谈索罗斯', 1995, 0),
('eq-s050', '成功的关键是能够在正确的时候下大注。', 'The key to success is being able to place big bets when you are right.', 'm-soros', '金融炼金术', 1987, 0);

-- 标签关联
INSERT OR IGNORE INTO quote_tags (quote_id, tag_id) VALUES
('eq-s001','t-risk'),('eq-s002','t-risk'),('eq-s003','t-market'),('eq-s004','t-risk'),('eq-s005','t-mindset'),
('eq-s006','t-market'),('eq-s007','t-market'),('eq-s008','t-market'),('eq-s009','t-risk'),('eq-s010','t-market'),
('eq-s011','t-risk'),('eq-s012','t-mindset'),('eq-s013','t-risk'),('eq-s014','t-market'),('eq-s015','t-market'),
('eq-s016','t-risk'),('eq-s017','t-mindset'),('eq-s018','t-market'),('eq-s019','t-market'),('eq-s020','t-market'),
('eq-s021','t-mindset'),('eq-s022','t-market'),('eq-s023','t-risk'),('eq-s024','t-market'),('eq-s025','t-risk'),
('eq-s026','t-learning'),('eq-s027','t-market'),('eq-s028','t-risk'),('eq-s029','t-market'),('eq-s030','t-risk'),
('eq-s031','t-market'),('eq-s032','t-value'),('eq-s033','t-market'),('eq-s034','t-risk'),('eq-s035','t-mindset'),
('eq-s036','t-market'),('eq-s037','t-mindset'),('eq-s038','t-risk'),('eq-s039','t-mindset'),('eq-s040','t-market'),
('eq-s041','t-mindset'),('eq-s042','t-market'),('eq-s043','t-mindset'),('eq-s044','t-market'),('eq-s045','t-risk'),
('eq-s046','t-market'),('eq-s047','t-market'),('eq-s048','t-risk'),('eq-s049','t-market'),('eq-s050','t-risk');

-- ============================================
-- 瑞·达利欧名言
-- ============================================

INSERT OR IGNORE INTO quotes (id, content_cn, content_en, master_id, source, source_year, is_featured) VALUES
('eq-d001', '我相信任何事情都有循环，成功的关键是顺应这些循环。', 'I believe everything has cycles, and the key to success is to go with these cycles.', 'm-dalio', '原则', 2017, 0),
('eq-d002', '大多数人在面对痛苦时会回避，而不是拥抱它并从中学习。', 'Most people avoid pain rather than embrace it and learn from it.', 'm-dalio', '原则', 2017, 0),
('eq-d003', '真相是成功最坚实的基础。', 'Truth is the most solid foundation for success.', 'm-dalio', '原则', 2017, 0),
('eq-d004', '最好的决策来自于把最好的思考与最好的决策过程结合起来。', 'The best decisions come from combining the best thinking with the best decision-making process.', 'm-dalio', '原则', 2017, 0),
('eq-d005', '我相信极度求真，极度透明。', 'I believe in being radically truthful and radically transparent.', 'm-dalio', '原则', 2017, 0),
('eq-d006', '失败是学习的最好机会，不要害怕失败。', 'Failure is the best opportunity to learn; do not be afraid of failure.', 'm-dalio', '原则', 2017, 0),
('eq-d007', '理解历史和经济周期可以帮助你做出更好的投资决策。', 'Understanding history and economic cycles can help you make better investment decisions.', 'm-dalio', '原则', 2017, 0),
('eq-d008', '大多数人的最大问题是没有开放的头脑。', 'Most peoples biggest problem is not having an open mind.', 'm-dalio', '原则', 2017, 0),
('eq-d009', '你想要什么，你就能得到什么，只要你愿意为此付出代价。', 'You can have whatever you want as long as you are willing to pay the price.', 'm-dalio', '原则', 2017, 0),
('eq-d010', '理解债务周期是理解经济的关键。', 'Understanding the debt cycle is the key to understanding the economy.', 'm-dalio', '原则', 2017, 0),
('eq-d011', '在市场上生存的关键是理解风险，而不是试图避免风险。', 'The key to survival in the market is understanding risk, not trying to avoid it.', 'm-dalio', '原则', 2017, 0),
('eq-d012', '我相信多角度思考，而不只是单一角度。', 'I believe in multi-perspective thinking, not just a single perspective.', 'm-dalio', '原则', 2017, 0),
('eq-d013', '把错误当作学习的机会，而不是失败的标志。', 'Treat mistakes as learning opportunities, not as signs of failure.', 'm-dalio', '原则', 2017, 0),
('eq-d014', '我建立桥水不是为了赚钱，而是为了理解经济运作的原理。', 'I built Bridgewater not to make money, but to understand how the economy works.', 'm-dalio', '原则', 2017, 0),
('eq-d015', '最成功的决策来自于把可信度加权与独立思考结合起来。', 'The most successful decisions come from combining believability weighting with independent thinking.', 'm-dalio', '原则', 2017, 0),
('eq-d016', '理解因果关系是预测未来的关键。', 'Understanding cause-and-effect relationships is the key to predicting the future.', 'm-dalio', '原则', 2017, 0),
('eq-d017', '我学到的一个最重要的教训是：差异化思维是成功的关键。', 'One of the most important lessons I learned is that differentiated thinking is the key to success.', 'm-dalio', '原则', 2017, 0),
('eq-d018', '不要把未来简单地从过去推断，因为情况会变化。', 'Do not extrapolate the future simply from the past because situations change.', 'm-dalio', '原则', 2017, 0),
('eq-d019', '成功的生活需要平衡，接受现实并努力改变。', 'A successful life requires balance, accepting reality while striving to change it.', 'm-dalio', '原则', 2017, 0),
('eq-d020', '理解他人的视角可以帮助你做出更好的决策。', 'Understanding others perspectives can help you make better decisions.', 'm-dalio', '原则', 2017, 0),
('eq-d021', '投资的核心是理解风险与回报的关系。', 'The core of investing is understanding the relationship between risk and return.', 'm-dalio', '原则', 2017, 0),
('eq-d022', '我相信通过原则生活，而不是通过记忆生活。', 'I believe in living by principles rather than by memory.', 'm-dalio', '原则', 2017, 0),
('eq-d023', '大多数痛苦来自于你期望的和你得到的之间的差距。', 'Most pain comes from the gap between what you expect and what you get.', 'm-dalio', '原则', 2017, 0),
('eq-d024', '理解自己的弱点是改进的第一步。', 'Understanding your own weaknesses is the first step to improvement.', 'm-dalio', '原则', 2017, 0),
('eq-d025', '好的想法需要经过压力测试才能成为好决策。', 'Good ideas need to be stress-tested to become good decisions.', 'm-dalio', '原则', 2017, 0),
('eq-d026', '我相信系统性思考，而不只是线性思考。', 'I believe in systemic thinking, not just linear thinking.', 'm-dalio', '原则', 2017, 0),
('eq-d027', '在投资中，最重要的事情是理解你在赌什么。', 'In investing, the most important thing is understanding what you are betting on.', 'm-dalio', '原则', 2017, 0),
('eq-d028', '大多数人在决策时会受到情绪的影响。', 'Most people are influenced by emotions when making decisions.', 'm-dalio', '原则', 2017, 0),
('eq-d029', '理解历史周期可以帮助你避免重蹈覆辙。', 'Understanding historical cycles can help you avoid repeating mistakes.', 'm-dalio', '原则', 2017, 0),
('eq-d030', '我相信想法的精英制度，让最好的想法胜出。', 'I believe in an idea meritocracy, letting the best ideas win.', 'm-dalio', '原则', 2017, 0),
('eq-d031', '痛苦加反思等于进步，这是我在生活中学到的最重要的公式。', 'Pain plus reflection equals progress; this is the most important formula I have learned in life.', 'm-dalio', '原则', 2017, 0),
('eq-d032', '不要把希望和现实混为一谈。', 'Do not confuse hope with reality.', 'm-dalio', '原则', 2017, 0),
('eq-d033', '成功的关键不是避免错误，而是从错误中快速学习。', 'The key to success is not avoiding mistakes, but learning quickly from them.', 'm-dalio', '原则', 2017, 0),
('eq-d034', '我相信多元化和分散投资的重要性。', 'I believe in the importance of diversification and spread investing.', 'm-dalio', '原则', 2017, 0),
('eq-d035', '理解不同资产类别的相关性是风险管理的基础。', 'Understanding correlations between different asset classes is the foundation of risk management.', 'm-dalio', '原则', 2017, 0),
('eq-d036', '在市场上最重要的不是你的看法对不对，而是你的看法对的时候你赚了多少。', 'In the market, the most important thing is not whether your view is right, but how much you make when you are right.', 'm-dalio', '原则', 2017, 0),
('eq-d037', '我相信通过数据和逻辑做决策，而不是通过情绪。', 'I believe in making decisions through data and logic, not through emotions.', 'm-dalio', '原则', 2017, 0),
('eq-d038', '理解经济的运作原理是投资成功的基础。', 'Understanding how the economy works is the foundation of investment success.', 'm-dalio', '原则', 2017, 0),
('eq-d039', '我相信每个人都有自己的优点和缺点，关键是发挥优点，管理缺点。', 'I believe everyone has their own strengths and weaknesses; the key is to leverage strengths and manage weaknesses.', 'm-dalio', '原则', 2017, 0),
('eq-d040', '在处理问题时，要分清主要矛盾和次要矛盾。', 'When handling problems, distinguish between primary and secondary contradictions.', 'm-dalio', '原则', 2017, 0),
('eq-d041', '我相信极度开放，同时极度有原则。', 'I believe in being radically open-minded while being radically principled.', 'm-dalio', '原则', 2017, 0),
('eq-d042', '理解你周围人的优点和缺点可以帮助你更好地与他们合作。', 'Understanding the strengths and weaknesses of people around you can help you cooperate better with them.', 'm-dalio', '原则', 2017, 0),
('eq-d043', '成功的决策需要好的输入和好的处理过程。', 'Successful decisions require good inputs and good processing.', 'm-dalio', '原则', 2017, 0),
('eq-d044', '我相信在决策时要保持冷静，不受情绪影响。', 'I believe in staying calm when making decisions and not being influenced by emotions.', 'm-dalio', '原则', 2017, 0),
('eq-d045', '理解政治和经济之间的互动是预测未来的关键。', 'Understanding the interaction between politics and economics is the key to predicting the future.', 'm-dalio', '原则', 2017, 0),
('eq-d046', '我相信通过写下来的原则来指导决策。', 'I believe in guiding decisions through written principles.', 'm-dalio', '原则', 2017, 0),
('eq-d047', '理解债务和货币的运作原理是理解经济危机的关键。', 'Understanding how debt and money work is the key to understanding economic crises.', 'm-dalio', '原则', 2017, 0),
('eq-d048', '我相信建立系统来做出好的决策，而不是依赖直觉。', 'I believe in building systems to make good decisions rather than relying on intuition.', 'm-dalio', '原则', 2017, 0),
('eq-d049', '理解不同类型风险的特性是资产配置的基础。', 'Understanding the characteristics of different types of risk is the foundation of asset allocation.', 'm-dalio', '原则', 2017, 0),
('eq-d050', '我相信持续学习是成功的关键。', 'I believe continuous learning is the key to success.', 'm-dalio', '原则', 2017, 0);

-- 标签关联
INSERT OR IGNORE INTO quote_tags (quote_id, tag_id) VALUES
('eq-d001','t-market'),('eq-d002','t-learning'),('eq-d003','t-philosophy'),('eq-d004','t-philosophy'),('eq-d005','t-mindset'),
('eq-d006','t-learning'),('eq-d007','t-market'),('eq-d008','t-learning'),('eq-d009','t-philosophy'),('eq-d010','t-market'),
('eq-d011','t-risk'),('eq-d012','t-learning'),('eq-d013','t-learning'),('eq-d014','t-market'),('eq-d015','t-philosophy'),
('eq-d016','t-learning'),('eq-d017','t-learning'),('eq-d018','t-market'),('eq-d019','t-philosophy'),('eq-d020','t-learning'),
('eq-d021','t-risk'),('eq-d022','t-philosophy'),('eq-d023','t-philosophy'),('eq-d024','t-learning'),('eq-d025','t-philosophy'),
('eq-d026','t-learning'),('eq-d027','t-risk'),('eq-d028','t-mindset'),('eq-d029','t-learning'),('eq-d030','t-philosophy'),
('eq-d031','t-learning'),('eq-d032','t-mindset'),('eq-d033','t-learning'),('eq-d034','t-risk'),('eq-d035','t-risk'),
('eq-d036','t-risk'),('eq-d037','t-mindset'),('eq-d038','t-market'),('eq-d039','t-philosophy'),('eq-d040','t-learning'),
('eq-d041','t-mindset'),('eq-d042','t-philosophy'),('eq-d043','t-philosophy'),('eq-d044','t-mindset'),('eq-d045','t-market'),
('eq-d046','t-philosophy'),('eq-d047','t-market'),('eq-d048','t-philosophy'),('eq-d049','t-risk'),('eq-d050','t-learning');

-- ============================================
-- 霍华德·马克斯名言
-- ============================================

INSERT OR IGNORE INTO quotes (id, content_cn, content_en, master_id, source, source_year, is_featured) VALUES
('eq-h001', '在市场过热时保持怀疑，在市场恐慌时保持勇气。', 'Remain skeptical when the market is overheating, and courageous when the market panics.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h002', '第二层思维是区分普通投资者和优秀投资者的关键。', 'Second-level thinking is the key to distinguishing ordinary investors from excellent ones.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h003', '高风险只能带来高回报的说法是错误的。', 'The statement that high risk can only lead to high returns is wrong.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h004', '市场价格已经反映了大多数人的共识。', 'Market prices already reflect the consensus of most people.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h005', '投资的成功取决于你做得比市场更好，而不只是与市场一致。', 'Investment success depends on you doing better than the market, not just matching it.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h006', '最危险的投资是那些看起来最安全的投资。', 'The most dangerous investments are those that look safest.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h007', '理解风险是投资成功的关键，而不是追求回报。', 'Understanding risk is the key to investment success, not pursuing returns.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h008', '市场的周期性是不可避免的，关键是知道我们在周期中的位置。', 'Market cyclicality is inevitable; the key is knowing where we are in the cycle.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h009', '好的投资是那些在买入时就能够提供安全边际的投资。', 'Good investments are those that provide a margin of safety when bought.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h010', '在投资中，过度自信是最大的敌人。', 'In investing, overconfidence is the biggest enemy.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h011', '耐心等待合适的价格是投资成功的关键。', 'Patiently waiting for the right price is the key to investment success.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h012', '分散投资可以降低风险，但不能消除风险。', 'Diversification can reduce risk, but cannot eliminate it.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h013', '在投资中，最重要的是不要亏钱。', 'In investing, the most important thing is not to lose money.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h014', '逆向投资意味着在别人卖出时买入，在别人买入时卖出。', 'Contrarian investing means buying when others sell and selling when others buy.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h015', '理解估值是投资的基础，而不是追逐热门。', 'Understanding valuation is the foundation of investing, not chasing popular stocks.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h016', '投资于不确定性是最大的错误。', 'Investing in uncertainty is the biggest mistake.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h017', '在市场顶部时保持谦虚，在市场底部时保持贪婪。', 'Stay humble at market tops and greedy at market bottoms.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h018', '好的投资需要耐心和纪律。', 'Good investing requires patience and discipline.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h019', '风险是投资中最重要的考虑因素。', 'Risk is the most important consideration in investing.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h020', '理解周期可以帮助你避免在顶部买入，在底部卖出。', 'Understanding cycles can help you avoid buying at the top and selling at the bottom.', 'm-marks', '周期', 2018, 0),
('eq-h021', '在投资中，情绪是最大的敌人。', 'In investing, emotions are the biggest enemy.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h022', '成功的投资需要你能够在别人恐惧时保持冷静。', 'Successful investing requires you to stay calm when others are fearful.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h023', '投资回报与所承担的风险之间没有简单的线性关系。', 'There is no simple linear relationship between investment returns and risk assumed.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h024', '好的投资者在别人不想要的时候买入。', 'Good investors buy when others do not want it.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h025', '理解市场的钟摆特性可以帮助你做出更好的投资决策。', 'Understanding the pendulum nature of markets can help you make better investment decisions.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h026', '在投资中，最重要的不是你的看法对不对，而是你知道你可能是错的。', 'In investing, the most important thing is not whether your view is right, but knowing you might be wrong.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h027', '好的投资者会在市场过度乐观时变得谨慎。', 'Good investors become cautious when the market is overly optimistic.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h028', '理解自己不知道什么是投资智慧的开始。', 'Understanding what you do not know is the beginning of investment wisdom.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h029', '在投资中，避免错误比追求正确更重要。', 'In investing, avoiding mistakes is more important than pursuing correctness.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h030', '好的投资是那些你可以在最坏情况下也能持有的投资。', 'Good investments are those you can hold even in the worst case.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h031', '在投资中，价格是最重要的变量。', 'In investing, price is the most important variable.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h032', '成功的投资者是那些能够独立思考的人。', 'Successful investors are those who can think independently.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h033', '理解心理因素在投资中的作用是至关重要的。', 'Understanding the role of psychological factors in investing is crucial.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h034', '在市场繁荣时要想到风险，在市场萧条时要想到机会。', 'Think about risk when the market is booming, and think about opportunities when the market is depressed.', 'm-marks', '周期', 2018, 0),
('eq-h035', '好的投资者会在投资前做充分的尽职调查。', 'Good investors do thorough due diligence before investing.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h036', '理解价值的来源是投资成功的关键。', 'Understanding the sources of value is the key to investment success.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h037', '在投资中，便宜是硬道理。', 'In investing, cheapness is hard truth.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h038', '成功的投资不是关于预测未来，而是关于为未来做准备。', 'Successful investing is not about predicting the future, but about being prepared for it.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h039', '在投资中，最重要的品质是耐心和理性。', 'In investing, the most important qualities are patience and rationality.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h040', '理解市场的历史可以帮助你避免犯同样的错误。', 'Understanding market history can help you avoid making the same mistakes.', 'm-marks', '周期', 2018, 0),
('eq-h041', '好的投资是那些即使在不利情况下也能保护你本金的的投资。', 'Good investments are those that protect your principal even in adverse conditions.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h042', '在投资中，你需要知道什么时候应该坚持，什么时候应该放弃。', 'In investing, you need to know when to persist and when to give up.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h043', '理解风险溢价是理解投资回报的基础。', 'Understanding risk premium is the foundation of understanding investment returns.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h044', '在市场顶部时，风险最大，回报最小。', 'At market tops, risk is highest and returns are smallest.', 'm-marks', '周期', 2018, 0),
('eq-h045', '好的投资者会时刻关注风险，而不是只关注回报。', 'Good investors always focus on risk, not just on returns.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h046', '在投资中，过度反应是人性的一部分。', 'In investing, overreaction is part of human nature.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h047', '理解流动性在投资中的作用是重要的。', 'Understanding the role of liquidity in investing is important.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h048', '成功的投资者知道什么时候应该逆向而行。', 'Successful investors know when they should go against the grain.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h049', '在投资中，便宜和优质同样重要。', 'In investing, cheapness and quality are equally important.', 'm-marks', '投资最重要的事', 2011, 0),
('eq-h050', '理解自己为什么能够赚钱是持续成功的关键。', 'Understanding why you make money is the key to continued success.', 'm-marks', '投资最重要的事', 2011, 0);

-- 标签关联
INSERT OR IGNORE INTO quote_tags (quote_id, tag_id) VALUES
('eq-h001','t-contrarian'),('eq-h002','t-learning'),('eq-h003','t-risk'),('eq-h004','t-market'),('eq-h005','t-market'),
('eq-h006','t-risk'),('eq-h007','t-risk'),('eq-h008','t-market'),('eq-h009','t-value'),('eq-h010','t-mindset'),
('eq-h011','t-longterm'),('eq-h012','t-risk'),('eq-h013','t-risk'),('eq-h014','t-contrarian'),('eq-h015','t-value'),
('eq-h016','t-risk'),('eq-h017','t-market'),('eq-h018','t-mindset'),('eq-h019','t-risk'),('eq-h020','t-market'),
('eq-h021','t-mindset'),('eq-h022','t-contrarian'),('eq-h023','t-risk'),('eq-h024','t-contrarian'),('eq-h025','t-market'),
('eq-h026','t-mindset'),('eq-h027','t-contrarian'),('eq-h028','t-circle'),('eq-h029','t-risk'),('eq-h030','t-risk'),
('eq-h031','t-value'),('eq-h032','t-contrarian'),('eq-h033','t-mindset'),('eq-h034','t-market'),('eq-h035','t-learning'),
('eq-h036','t-value'),('eq-h037','t-value'),('eq-h038','t-risk'),('eq-h039','t-mindset'),('eq-h040','t-learning'),
('eq-h041','t-risk'),('eq-h042','t-mindset'),('eq-h043','t-risk'),('eq-h044','t-market'),('eq-h045','t-risk'),
('eq-h046','t-market'),('eq-h047','t-risk'),('eq-h048','t-contrarian'),('eq-h049','t-value'),('eq-h050','t-learning');
