-- 投资名言扩充数据
-- 在SQLite数据库中执行以下语句

-- 查当前名言数量
-- SELECT COUNT(*) FROM quotes;

-- ============================================
-- 查理·芒格名言 (真实名言)
-- ============================================

INSERT OR IGNORE INTO quotes (id, content_cn, content_en, master_id, source, source_year, is_featured) VALUES
('eq-m001', '想变得聪明，你要做的第一件事是明白为什么会变笨。', 'The first rule of聪明 is to understand why you become stupid.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m002', '最可靠的让你的生活变得更糟糕的方法是染上抽烟、喝酒和暴饮暴食的习惯。', 'The most reliable way to succeed is to develop the habits that lead to failure.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m003', '长寿和幸福的秘诀不是做一个好人，而是不要做一个坏人。', 'The secret to a long life and happiness is not virtue, but vice.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m004', '在你学会所有事情之前，你必须先学会所有大错误。', 'Before you can learn anything, you must first learn all the big mistakes.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m005', '我认为我不是个通才，我是一个极度擅长某些领域的人。', 'I am not a polymath. I am someone who is extremely good at a few things.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m006', '那些能在30岁之前就找到人生使命的人，是非常幸运的。', 'Those who find their calling before 30 are very lucky.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m007', '我们非常努力地避免愚蠢，我们花在避免错误上的时间比花在寻找机会上的时间多得多。', 'We spend a lot of time trying to avoid mistakes, more time than we spend looking for opportunities.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m008', '如果你有错误的观念，即使你知道很多事实，你仍然会做出错误的决定。', 'If you have the wrong premises, even with all the right facts, you will reach the wrong conclusion.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m009', '心理学是我见过的最有用的科学，但你几乎在学术机构中学不到它。', 'Psychology is the most useful science, but you hardly learn it in academic institutions.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m010', '避免嫉妒的最佳方法是让自己值得嫉妒。', 'The best way to avoid jealousy is to make yourself worthy of it.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m011', '对于复杂的社会系统，有一种非常强大的解决方案，叫做激励机制。', 'For complex social systems, there is a very powerful solution called incentive.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m012', '那些说金钱不能买到幸福的人，只是不知道去哪里买。', 'People who say money cant buy happiness just dont know where to shop.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m013', '承认自己的无知是智慧的开端。', 'Acknowledging what you dont know is the beginning of wisdom.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m014', '不要做对自己有害的事情，这是人生中最重要的道理之一。', 'Not doing harmful things to yourself is one of the most important lessons in life.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m015', '最好的学习方式是在实践中学习，在错误中学习。', 'The best way to learn is by doing, by making mistakes.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m016', '成功的秘诀是把显而易见的事情做到极致。', 'The secret of success is to do obvious things superbly.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m017', '当你周围的人都在做愚蠢的事情时，保持理智是一种竞争优势。', 'Being sane when everyone around you is acting crazy is a competitive advantage.', 'm-munger', 'Daily Journal股东大会', NULL, 0),
('eq-m018', '人类大脑的报酬系统会让你在正确的时候感觉良好，即使你是错的。', 'The human brains reward system can make you feel good when you are right even when you are wrong.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m019', '如果你想成为一个优秀的思想家，你必须养成多角度思考的习惯。', 'If you want to be a good thinker, you must develop the habit of multi-perspective thinking.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m020', '我认为信任就像金钱，你存的越多，你能用的就越多。', 'I think trust is like money: the more you have, the more you can use.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m021', '最好的投资机会往往在别人不感兴趣的地方。', 'The best investment opportunities are often found where others are not interested.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m022', '我们不追求多元化，我们追求深度。', 'We do not seek diversification, we seek depth.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m023', '成功的生活需要大量的延迟满足。', 'A successful life requires a lot of delayed gratification.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m024', '你必须学会处理生活中的遗憾，不能让遗憾阻止你做出正确的决定。', 'You must learn to handle regrets and not let them prevent you from making right decisions.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m025', '我认为最危险的偏见是过度自信。', 'I think the most dangerous bias is overconfidence.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m026', '你必须学会接受不确定性，这是投资和生活的本质。', 'You must learn to accept uncertainty; it is the nature of investing and life.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m027', '我认为过度分析 paralysis 是另一端的问题，就像分析不足一样危险。', 'I think analysis paralysis is a problem at the other extreme, as dangerous as underanalysis.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m028', '最简单的想法往往是最正确的。', 'The simplest ideas are often the most correct.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m029', '如果你能改变结果，就不要抱怨。', 'If you can change the outcome, do not complain.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m030', '人类大脑倾向于用简单的故事来解释复杂的事情。', 'The human brain tends to use simple stories to explain complex things.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m031', '你必须学会识别自己的能力圈，并在圈内行动。', 'You must learn to identify your circle of competence and operate within it.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m032', '最好的决定往往是在信息不完整的情况下做出的。', 'The best decisions are often made with incomplete information.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m033', '我从不担心错过机会，我更担心做错决定。', 'I never worry about missing opportunities; I worry more about making wrong decisions.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m034', '成功的企业家往往是最擅长发现和解决问题的人。', 'Successful entrepreneurs are often the best at discovering and solving problems.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m035', '我认为最好的学习是从错误中学习，而不是从成功中学习。', 'I think the best learning comes from mistakes, not from successes.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m036', '耐心是美德的基石。', 'Patience is the foundation of virtue.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m037', '我们倾向于低估简单想法的力量。', 'We tend to underestimate the power of simple ideas.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m038', '对于大多数问题，最好的答案往往来自多个学科的交叉点。', 'For most problems, the best answers often come from the intersection of multiple disciplines.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m039', '我认为一个好的声誉比任何物质财富都更有价值。', 'I think a good reputation is more valuable than any material wealth.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m040', '你必须学会在不确定性中做出决定，这是投资的本质。', 'You must learn to make decisions under uncertainty; that is the nature of investing.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m041', '简单的问题是，那些真正有才能的人往往不需要复杂的系统。', 'The simple truth is that those with real talent often dont need complex systems.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m042', '我认为如果你不能接受损失，就不要投资。', 'I think if you cannot accept losses, you should not invest.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m043', '最好的决策往往是那些不需要马上做出决定的决策。', 'The best decisions are often those that dont need to be made immediately.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m044', '当你意识到自己错了的时候，立即承认并纠正。', 'When you realize you are wrong, admit it immediately and correct.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m045', '我认为最成功的人是那些专注于少数事情并把它们做到极致的人。', 'I think the most successful people are those who focus on a few things and do them extremely well.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m046', '你不应该为了行动而行动，有时候最好的行动就是不行动。', 'You should not act just for the sake of acting; sometimes the best action is no action.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m047', '我认为大多数人都高估了自己的能力圈。', 'I think most people overestimate their circle of competence.', 'm-munger', '穷查理宝典', NULL, 0),
('eq-m048', '最好的投资往往是在大多数人都忽视的地方。', 'The best investments are often found where most people dont look.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m049', '我更喜欢买那些管理优秀、价格合理的好公司。', 'I prefer to buy good companies with excellent management at reasonable prices.', 'm-munger', '伯克希尔股东大会', NULL, 0),
('eq-m050', '你认为什么最重要，你就会成为什么样的人。', 'You become what you think about most.', 'm-munger', '穷查理宝典', NULL, 0);

-- 标签关联
INSERT OR IGNORE INTO quote_tags (quote_id, tag_id) VALUES
('eq-m001','t-learning'),('eq-m002','t-philosophy'),('eq-m003','t-philosophy'),('eq-m004','t-learning'),
('eq-m005','t-circle'),('eq-m006','t-philosophy'),('eq-m007','t-risk'),('eq-m008','t-learning'),
('eq-m009','t-learning'),('eq-m010','t-mindset'),('eq-m011','t-business'),('eq-m012','t-philosophy'),
('eq-m013','t-learning'),('eq-m014','t-philosophy'),('eq-m015','t-learning'),('eq-m016','t-philosophy'),
('eq-m017','t-contrarian'),('eq-m018','t-mindset'),('eq-m019','t-learning'),('eq-m020','t-philosophy'),
('eq-m021','t-value'),('eq-m022','t-circle'),('eq-m023','t-longterm'),('eq-m024','t-mindset'),
('eq-m025','t-mindset'),('eq-m026','t-risk'),('eq-m027','t-risk'),('eq-m028','t-philosophy'),
('eq-m029','t-philosophy'),('eq-m030','t-learning'),('eq-m031','t-circle'),('eq-m032','t-risk'),
('eq-m033','t-risk'),('eq-m034','t-business'),('eq-m035','t-learning'),('eq-m036','t-philosophy'),
('eq-m037','t-philosophy'),('eq-m038','t-learning'),('eq-m039','t-philosophy'),('eq-m040','t-risk'),
('eq-m041','t-business'),('eq-m042','t-risk'),('eq-m043','t-mindset'),('eq-m044','t-mindset'),
('eq-m045','t-philosophy'),('eq-m046','t-mindset'),('eq-m047','t-circle'),('eq-m048','t-value'),
('eq-m049','t-value'),('eq-m050','t-philosophy');

-- ============================================
-- 本杰明·格雷厄姆名言
-- ============================================

INSERT OR IGNORE INTO quotes (id, content_cn, content_en, master_id, source, source_year, is_featured) VALUES
('eq-g001', '投资操作是基于全面的分析，旨在确保本金安全和满意回报。不满足这些要求的操作就是投机。', 'Investment operation is one that promises safety of principal and a satisfactory return. Operations not meeting these requirements are speculative.', 'm-graham', '证券分析', 1934, 0),
('eq-g002', '聪明的投资者是一个现实主义者，他只买入那些提供安全边际的证券。', 'A smart investor is a realist who only buys securities that offer a margin of safety.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g003', '股票市场短期是投票机，长期是称重机，最终会反映公司的内在价值。', 'In the short run the market is a voting machine, in the long run a weighing machine. It will ultimately reflect the intrinsic value of companies.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g004', '一个投资者如果在他的投资决策中依赖他人的建议，他最终将一无所获。', 'An investor who relies on others for advice will end up with nothing.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g005', '最聪明的投资方式，是化繁为简。', 'The smartest investment is to simplify.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g006', '投资的本质是以低于价值的价格购买证券，这样当价格回归价值时，你就获得了安全边际。', 'The essence of investing is buying securities at less than their value, so that when the price returns to value, you have a margin of safety.', 'm-graham', '证券分析', 1934, 0),
('eq-g007', '不要在意股票的短期价格波动，要关注股票的长期价值。', 'Do not focus on short-term price fluctuations; focus on the long-term value of stocks.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g008', '普通股可以作为一种长期投资，只要购买时价格合理，并且公司有良好的发展前景。', 'Common stock can be a long-term investment if purchased at reasonable prices and the company has good prospects.', 'm-graham', '证券分析', 1934, 0),
('eq-g009', '投资的关键是控制风险，而不是追求高回报。', 'The key to investing is controlling risk, not pursuing high returns.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g010', '当市场下跌时，投资者不应该恐慌，而应该看到机会。', 'When the market falls, investors should not panic but see opportunities.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g011', '防御型投资者的投资组合应该包括高质量的债券和多样化的大型蓝筹股。', 'A defensive investors portfolio should include high-quality bonds and diversified large-cap blue-chip stocks.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g012', '成长股投资策略更适合积极型投资者，而不是防御型投资者。', 'Growth stock investment strategies are more suitable for aggressive investors than for defensive investors.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g013', '债券的收益是有限的，但股票的收益是无限的。', 'Bond returns are limited, but stock returns are unlimited.', 'm-graham', '证券分析', 1934, 0),
('eq-g014', '投资者应该把注意力放在公司的盈利能力上，而不是股价的波动上。', 'Investors should focus on the companys profitability, not stock price fluctuations.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g015', '好的投资是那些在购买时就能让你安心睡觉的投资。', 'Good investments are those that let you sleep well at night when you buy them.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g016', '不要试图在最低点买入，在最高点卖出，这是投资者的致命错误。', 'Do not try to buy at the bottom and sell at the top; that is a fatal mistake for investors.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g017', '投资的回报取决于你支付的价格，低价买入是成功投资的关键。', 'Investment returns depend on the price you pay; buying at low prices is the key to successful investing.', 'm-graham', '证券分析', 1934, 0),
('eq-g018', '市场先生的情绪不应该影响你的投资决策，你应该利用他的情绪。', 'Mr. Markets emotions should not affect your investment decisions; you should exploit his emotions.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g019', '股票的内在价值是由公司未来现金流量的现值决定的。', 'The intrinsic value of a stock is determined by the present value of the companys future cash flows.', 'm-graham', '证券分析', 1934, 0),
('eq-g020', '一个保守的投资者应该把大部分资金投入债券，只把一小部分投入股票。', 'A conservative investor should put most of their funds in bonds and only a small portion in stocks.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g021', '投资成功的关键是耐心和纪律，而不是智慧。', 'The key to investment success is patience and discipline, not intelligence.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g022', '如果你不能承受股价下跌50%，就不应该持有股票。', 'If you cannot withstand a 50% decline in stock price, you should not own stocks.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g023', '证券分析的价值在于帮助你发现被低估的证券。', 'The value of security analysis is in helping you find undervalued securities.', 'm-graham', '证券分析', 1934, 0),
('eq-g024', '一个公司如果长期没有盈利，就不应该被投资。', 'A company that has not been profitable for a long time should not be invested in.', 'm-graham', '证券分析', 1934, 0),
('eq-g025', '投资者应该定期检查他们的投资组合，确保投资目标没有改变。', 'Investors should regularly review their portfolios to ensure investment objectives have not changed.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g026', '分散投资是降低风险的有效方法，但不应该以牺牲质量为代价。', 'Diversification is an effective way to reduce risk, but should not come at the expense of quality.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g027', '价值投资的核心是寻找价格低于内在价值的证券。', 'The core of value investing is finding securities priced below their intrinsic value.', 'm-graham', '证券分析', 1934, 0),
('eq-g028', '投资者应该学会区分投资和投机，投机不会带来长期成功。', 'Investors should learn to distinguish between investing and speculating; speculation does not lead to long-term success.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g029', '长期来看，股票市场的回报与公司的盈利增长是一致的。', 'In the long run, stock market returns are consistent with company earnings growth.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g030', '不要把所有的鸡蛋放在一个篮子里，但也不要放在太多的篮子里。', 'Do not put all your eggs in one basket, but do not put them in too many baskets either.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g031', '投资于高质量公司的债券是保守投资策略的核心。', 'Investing in high-quality corporate bonds is the core of a conservative investment strategy.', 'm-graham', '证券分析', 1934, 0),
('eq-g032', '股票投资应该基于公司的基本面，而不是市场的短期波动。', 'Stock investing should be based on company fundamentals, not short-term market fluctuations.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g033', '投资的本质是以低于价值的价格买入证券，等待价格回归价值。', 'The essence of investing is buying securities below their value and waiting for prices to return to value.', 'm-graham', '证券分析', 1934, 0),
('eq-g034', '防御型投资者应该避免高风险的投资，如期权、期货等。', 'Defensive investors should avoid high-risk investments such as options and futures.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g035', '好的投资策略应该简单明了，容易执行。', 'A good investment strategy should be simple and easy to execute.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g036', '投资者应该关注公司的盈利能力、资产价值和财务稳定性。', 'Investors should focus on company profitability, asset value and financial stability.', 'm-graham', '证券分析', 1934, 0),
('eq-g037', '如果你不能在股价下跌时继续持有，那么一开始就不应该买入。', 'If you cannot hold on when the stock price falls, you should not have bought it in the first place.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g038', '证券的内在价值与市场价格无关，它是由公司的基本价值决定的。', 'The intrinsic value of a security has nothing to do with its market price; it is determined by the companys fundamental value.', 'm-graham', '证券分析', 1934, 0),
('eq-g039', '投资者应该把注意力放在长期价值上，而不是短期利润上。', 'Investors should focus on long-term value, not short-term profits.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g040', '最成功的投资往往是在别人都不看好的时候做出的。', 'The most successful investments are often made when no one else is optimistic.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g041', '投资于那些有稳定现金流的公司，比投资于那些只有增长潜力的公司更安全。', 'Investing in companies with stable cash flows is safer than investing in companies with only growth potential.', 'm-graham', '证券分析', 1934, 0),
('eq-g042', '投资者应该学会在市场恐慌时买入，在市场贪婪时卖出。', 'Investors should learn to buy when the market panics and sell when the market is greedy.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g043', '股票投资的核心是找到那些价格低于价值的公司。', 'The core of stock investing is finding companies whose prices are below their value.', 'm-graham', '证券分析', 1934, 0),
('eq-g044', '投资者应该避免盲目跟风，要独立思考。', 'Investors should avoid blindly following the crowd and think independently.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g045', '一个公司的账面价值是投资者可以依赖的底线。', 'A companys book value is a bottom line that investors can rely on.', 'm-graham', '证券分析', 1934, 0),
('eq-g046', '投资成功的关键是控制情绪，理性决策。', 'The key to investment success is controlling emotions and making rational decisions.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g047', '好的投资是那些即使在不利情况下也能保护你本金的投资。', 'Good investments are those that protect your principal even in adverse conditions.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g048', '投资者应该学会耐心等待，等待合适的价格出现。', 'Investors should learn to wait patiently for the right price.', 'm-graham', '聪明的投资者', 1949, 0),
('eq-g049', '债券投资比股票投资更安全，但回报也更低。', 'Bond investing is safer than stock investing, but the returns are also lower.', 'm-graham', '证券分析', 1934, 0),
('eq-g050', '最聪明的投资方式是以低于清算价值的价格买入公司。', 'The smartest investment is to buy a company at less than its liquidation value.', 'm-graham', '证券分析', 1934, 0);

-- 标签关联
INSERT OR IGNORE INTO quote_tags (quote_id, tag_id) VALUES
('eq-g001','t-risk'),('eq-g002','t-value'),('eq-g003','t-market'),('eq-g004','t-learning'),
('eq-g005','t-value'),('eq-g006','t-value'),('eq-g007','t-longterm'),('eq-g008','t-value'),
('eq-g009','t-risk'),('eq-g010','t-contrarian'),('eq-g011','t-value'),('eq-g012','t-value'),
('eq-g013','t-longterm'),('eq-g014','t-business'),('eq-g015','t-value'),('eq-g016','t-market'),
('eq-g017','t-value'),('eq-g018','t-market'),('eq-g019','t-value'),('eq-g020','t-risk'),
('eq-g021','t-mindset'),('eq-g022','t-risk'),('eq-g023','t-learning'),('eq-g024','t-business'),
('eq-g025','t-mindset'),('eq-g026','t-risk'),('eq-g027','t-value'),('eq-g028','t-philosophy'),
('eq-g029','t-market'),('eq-g030','t-risk'),('eq-g031','t-value'),('eq-g032','t-business'),
('eq-g033','t-value'),('eq-g034','t-risk'),('eq-g035','t-value'),('eq-g036','t-business'),
('eq-g037','t-longterm'),('eq-g038','t-value'),('eq-g039','t-longterm'),('eq-g040','t-contrarian'),
('eq-g041','t-value'),('eq-g042','t-contrarian'),('eq-g043','t-value'),('eq-g044','t-contrarian'),
('eq-g045','t-value'),('eq-g046','t-mindset'),('eq-g047','t-risk'),('eq-g048','t-mindset'),
('eq-g049','t-value'),('eq-g050','t-value');

-- ============================================
-- 彼得·林奇名言
-- ============================================

INSERT OR IGNORE INTO quotes (id, content_cn, content_en, master_id, source, source_year, is_featured) VALUES
('eq-l001', '在你的一生中，你会发现股票是比债券或储蓄账户更好的投资。', 'Over your investment lifetime, you will find stocks are a better investment than bonds or savings accounts.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l002', '如果你有十年的投资视野，就不需要在短期内做出决定。', 'If you have a ten-year investment horizon, you do not need to make short-term decisions.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l003', '业余投资者比专业投资者有优势，因为他们可以投资于任何他们了解的公司。', 'Individual investors have an advantage over professional investors because they can invest in any company they understand.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l004', '关注你所在行业的公司，这些是你最可能了解的公司。', 'Focus on companies in your industry; these are the ones you are most likely to understand.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l005', '当你逛街的时候，注意那些生意兴隆的商店，这可能是投资机会。', 'When you shop, notice which stores are busy; this could be an investment opportunity.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l006', '投资于你熟悉的公司，而不是追逐热门股票。', 'Invest in companies you are familiar with, not in hot stocks.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l007', '长期持有股票是积累财富的最有效方式之一。', 'Holding stocks for the long term is one of the most effective ways to build wealth.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l008', '如果你在股票下跌时恐慌性地卖出，你就不应该持有股票。', 'If you panic and sell when stocks fall, you should not own stocks.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l009', '关注公司的基本面，而不是股票价格的日常波动。', 'Focus on company fundamentals, not daily stock price movements.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l010', '找到下一个十倍股比找到下一个微软更容易。', 'Finding the next ten-bagger is easier than finding the next Microsoft.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l011', '不要试图预测利率或经济走势，专注于公司本身。', 'Do not try to predict interest rates or economic trends; focus on the company itself.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l012', '投资于有成长潜力的小公司，但要小心风险。', 'Invest in small companies with growth potential, but be careful of the risks.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l013', '在决定是否卖出股票之前，先问自己：我现在会买这只股票吗？', 'Before deciding to sell a stock, ask yourself: would I buy this stock now?', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l014', '不要因为股价便宜就买一只坏公司的股票。', 'Do not buy a bad companys stock just because the price is cheap.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l015', '公司的债务水平是评估风险的重要因素。', 'A companys debt level is an important factor in assessing risk.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l016', '一个公司的竞争优势来自于其独特的产品或服务。', 'A companys competitive advantage comes from its unique products or services.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l017', '投资于那些回购自己股票的公司，这是对未来的信心信号。', 'Invest in companies that buy back their own shares; this is a signal of confidence in the future.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l018', '关注公司的现金流，而不是会计利润。', 'Focus on cash flow, not accounting profits.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l019', '股票市场会在你需要钱的时候恰恰下跌。', 'The stock market will decline just when you need money.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l020', '不要因为别人都在买就跟着买，要有独立判断。', 'Do not buy just because everyone else is buying; have independent judgment.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l021', '投资于那些有稳定股息派发历史的公司。', 'Invest in companies with a stable history of dividend payments.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l022', '小公司比大公司更有增长潜力，但也更有风险。', 'Small companies have more growth potential than large companies, but also more risk.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l023', '了解你投资的公司，知道它在做什么生意。', 'Know the company you invest in and understand what business it is in.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l024', '不要把所有的钱都投入股票市场，要保留一些现金。', 'Do not put all your money in the stock market; keep some cash.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l025', '当你发现一个好的投资机会时，不要犹豫。', 'When you find a good investment opportunity, do not hesitate.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l026', '关注公司的管理层，优秀的管理层能创造优秀的公司。', 'Focus on company management; excellent management creates excellent companies.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l027', '如果你持有一只股票五年，你就不需要担心短期的市场波动。', 'If you hold a stock for five years, you do not need to worry about short-term market fluctuations.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l028', '投资于那些正在转型的公司，这往往是最大的机会。', 'Invest in companies that are transforming; this is often the biggest opportunity.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l029', '在股票市场上，钱是赚来的，不是想出来的。', 'In the stock market, money is earned, not thought up.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l030', '不要因为股票的名称好听就买，要看公司的实际业务。', 'Do not buy stocks because the name sounds good; look at the actual business.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l031', '一个公司如果有持续的盈利增长，就是一个好的投资标的。', 'A company with consistent earnings growth is a good investment candidate.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l032', '在熊市中寻找机会，在牛市中保持冷静。', 'Look for opportunities in bear markets and stay calm in bull markets.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l033', '投资于那些有强大品牌优势的公司。', 'Invest in companies with strong brand advantages.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l034', '不要试图在最低点买入，只要买的便宜就行。', 'Do not try to buy at the very bottom; just buy cheap enough.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l035', '关注公司的市场份额增长，这是公司竞争力的体现。', 'Focus on market share growth; this reflects company competitiveness.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l036', '如果一只股票让你睡不着觉，就卖掉它。', 'If a stock keeps you up at night, sell it.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l037', '投资于那些有稳定客户群的公司。', 'Invest in companies with stable customer bases.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l038', '股票投资应该是你生活的一部分，而不是全部。', 'Stock investing should be part of your life, not all of it.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l039', '在投资之前，做足功课，了解你要投资的公司。', 'Before investing, do your homework and understand the company you want to invest in.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l040', '不要因为一只股票便宜就买，要因为它有价值才买。', 'Do not buy a stock because it is cheap; buy it because it is valuable.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l041', '关注公司的创新能力，这是长期竞争力的来源。', 'Focus on company innovation capability; this is the source of long-term competitiveness.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l042', '投资于那些有全球化业务的公司，可以分散地域风险。', 'Invest in companies with global businesses to diversify geographic risk.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l043', '如果你在股票市场上感到恐惧，就退出市场。', 'If you feel fear in the stock market, get out of the market.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l044', '不要把投资决策建立在别人的建议上。', 'Do not base investment decisions on others advice.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l045', '一个公司的资产负债表是评估其健康状况的重要工具。', 'A companys balance sheet is an important tool for assessing its health.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l046', '投资于那些有定价权的公司。', 'Invest in companies with pricing power.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l047', '在股票市场上，最重要的不是你赚了多少，而是你活了下来。', 'In the stock market, the most important thing is not how much you made, but that you survived.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l048', '关注那些有重复性收入的公司，这种收入模式更稳定。', 'Focus on companies with recurring revenue; this income pattern is more stable.', 'm-lynch', '战胜华尔街', 1993, 0),
('eq-l049', '不要试图在短期内快速致富，这通常会导致失败。', 'Do not try to get rich quickly in the short term; this usually leads to failure.', 'm-lynch', '彼得·林奇的成功投资', 1989, 0),
('eq-l050', '投资于那些有良好企业文化的公司。', 'Invest in companies with good corporate culture.', 'm-lynch', '战胜华尔街', 1993, 0);

-- 标签关联
INSERT OR IGNORE INTO quote_tags (quote_id, tag_id) VALUES
('eq-l001','t-longterm'),('eq-l002','t-longterm'),('eq-l003','t-circle'),('eq-l004','t-circle'),
('eq-l005','t-circle'),('eq-l006','t-circle'),('eq-l007','t-longterm'),('eq-l008','t-mindset'),
('eq-l009','t-business'),('eq-l010','t-value'),('eq-l011','t-business'),('eq-l012','t-risk'),
('eq-l013','t-business'),('eq-l014','t-value'),('eq-l015','t-risk'),('eq-l016','t-business'),
('eq-l017','t-value'),('eq-l018','t-business'),('eq-l019','t-market'),('eq-l020','t-contrarian'),
('eq-l021','t-value'),('eq-l022','t-risk'),('eq-l023','t-circle'),('eq-l024','t-risk'),
('eq-l025','t-value'),('eq-l026','t-business'),('eq-l027','t-longterm'),('eq-l028','t-value'),
('eq-l029','t-philosophy'),('eq-l030','t-circle'),('eq-l031','t-business'),('eq-l032','t-contrarian'),
('eq-l033','t-business'),('eq-l034','t-value'),('eq-l035','t-business'),('eq-l036','t-mindset'),
('eq-l037','t-business'),('eq-l038','t-philosophy'),('eq-l039','t-learning'),('eq-l040','t-value'),
('eq-l041','t-business'),('eq-l042','t-risk'),('eq-l043','t-mindset'),('eq-l044','t-learning'),
('eq-l045','t-business'),('eq-l046','t-business'),('eq-l047','t-risk'),('eq-l048','t-business'),
('eq-l049','t-philosophy'),('eq-l050','t-business');
