-- ============================================
-- 约翰·博格名言
-- ============================================

INSERT OR IGNORE INTO quotes (id, content_cn, content_en, master_id, source, source_year, is_featured) VALUES
('eq-j001', '对于大多数投资者来说，指数基金是唯一理性的投资选择。', 'For most investors, index funds are the only rational investment choice.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j002', '不要试图战胜市场，市场就是市场。', 'Do not try to beat the market; the market is the market.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j003', '低成本是决定基金长期回报的关键因素。', 'Low cost is the key factor determining long-term fund returns.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j004', '时间是你最大的敌人，也是你最大的朋友。', 'Time is your greatest enemy, and also your greatest friend.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j005', '基金行业的商业模式是建立在投资者亏钱的基础上的。', 'The mutual fund industry business model is built on investors losing money.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j006', '如果你不能控制成本，你就不能控制回报。', 'If you cannot control costs, you cannot control returns.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j007', '在投资的游戏中，成本是确定的，回报是不确定的。', 'In the investment game, costs are certain, returns are uncertain.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j008', '指数基金的革命性在于它承认你无法战胜市场。', 'The revolution of index funds lies in its acknowledgment that you cannot beat the market.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j009', '基金持有人的最大敌人是基金业本身。', 'The biggest enemy of fund holders is the fund industry itself.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j010', '选择一个低成本指数基金，然后坚持到底。', 'Choose a low-cost index fund and stick with it.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j011', '投资的回报来自于经济增长和企业盈利，而不是基金经理的能力。', 'Investment returns come from economic growth and corporate earnings, not from fund managers abilities.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j012', '在长期投资中，成本的重要性超过了一切。', 'In long-term investing, the importance of costs exceeds everything.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j013', '主动管理基金的失败是系统性、结构性的，不是偶然的。', 'The failure of active fund management is systemic and structural, not accidental.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j014', '不要相信那些声称能够战胜市场的基金经理。', 'Do not believe fund managers who claim they can beat the market.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j015', '指数基金让普通投资者能够以低成本获得市场回报。', 'Index funds allow ordinary investors to get market returns at low cost.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j016', '在投资中，简单是最好的策略。', 'In investing, simplicity is the best strategy.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j017', '投资的真谛是承担市场风险，获得市场回报。', 'The essence of investing is taking market risk to get market returns.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j018', '不要试图在时机的选择上浪费时间，没有人有这个能力。', 'Do not waste time trying to time the market; no one has that ability.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j019', '基金行业的营销部门往往比投资部门更强大。', 'The mutual fund industry marketing department is often more powerful than the investment department.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j020', '在一个竞争激烈的市场中，战胜市场是不可能的。', 'In a highly competitive market, beating the market is impossible.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j021', '投资者应该专注于降低投资成本，而不是寻找更好的投资机会。', 'Investors should focus on reducing investment costs, not on finding better investment opportunities.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j022', '指数基金是民主化投资的工具。', 'Index funds are tools for democratizing investing.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j023', '大多数投资者应该投资债券和股票指数基金。', 'Most investors should invest in bond and stock index funds.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j024', '投资的四定律：低成本、分散投资、定期定投、长期持有。', 'The four laws of investing: low cost, diversification, dollar-cost averaging, long-term holding.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j025', '在一个完全有效的市场中，指数基金是最优选择。', 'In a perfectly efficient market, index funds are the optimal choice.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j026', '投资者应该抵制住追逐热门基金的诱惑。', 'Investors should resist the temptation to chase hot funds.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j027', '长期来看，主动管理基金几乎总是输给被动指数基金。', 'In the long run, active funds almost always lose to passive index funds.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j028', '不要被基金的过去业绩所迷惑。', 'Do not be fooled by a funds past performance.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j029', '投资回报等于市场回报减去成本。', 'Investment return equals market return minus cost.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j030', '投资者应该把注意力放在长期目标上，而不是短期波动。', 'Investors should focus on long-term goals, not short-term fluctuations.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j031', '复利的力量是惊人的，但成本会侵蚀大部分收益。', 'The power of compounding is amazing, but costs erode most of the gains.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j032', '低成本是投资者唯一可以控制的变量。', 'Low cost is the only variable that investors can control.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j033', '基金行业的秘密是：它为投资者创造的价值远低于它收取的费用。', 'The mutual fund industry secret is: it creates far less value for investors than the fees it charges.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j034', '在投资中，简单的解决方案往往比复杂的更好。', 'In investing, simple solutions are often better than complex ones.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j035', '投资者应该避免那些高换手率的基金。', 'Investors should avoid funds with high turnover rates.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j036', '指数化投资是长期投资成功的秘诀。', 'Index investing is the secret to long-term investment success.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j037', '不要相信那些声称能够预测市场的顾问。', 'Do not believe advisors who claim to be able to predict the market.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j038', '投资者应该把时间和精力放在资产配置上，而不是选择基金上。', 'Investors should focus their time and energy on asset allocation, not on fund selection.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j039', '低成本指数基金是大多数投资者最好的选择。', 'Low-cost index funds are the best choice for most investors.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j040', '在投资中，耐心和纪律是成功的关键。', 'In investing, patience and discipline are the keys to success.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j041', '基金行业收取的费用远超过它提供的价值。', 'The mutual fund industry charges far more than the value it provides.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j042', '投资者应该相信市场，而不是相信基金经理。', 'Investors should believe in the market, not in fund managers.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j043', '在一个竞争激烈的市场中，低成本是唯一的优势。', 'In a competitive market, low cost is the only advantage.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j044', '指数基金让投资变得简单、便宜、有效。', 'Index funds make investing simple, cheap, and efficient.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j045', '投资者应该避免追逐过去业绩最好的基金。', 'Investors should avoid chasing funds with the best past performance.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j046', '在长期投资中，成本比时机更重要。', 'In long-term investing, cost is more important than timing.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j047', '被动投资是长期投资成功的最佳策略。', 'Passive investing is the best strategy for long-term investment success.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j048', '不要被花哨的投资策略所迷惑，简单往往更好。', 'Do not be fooled by fancy investment strategies; simple is often better.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j049', '投资的本质是获得经济增长带来的收益。', 'The essence of investing is to obtain returns from economic growth.', 'm-bogle', '共同基金常识', 1999, 0),
('eq-j050', '指数基金是投资民主化的最大成就。', 'Index funds are the greatest achievement of investment democratization.', 'm-bogle', '共同基金常识', 1999, 0);

-- 标签关联
INSERT OR IGNORE INTO quote_tags (quote_id, tag_id) VALUES
('eq-j001','t-value'),('eq-j002','t-market'),('eq-j003','t-value'),('eq-j004','t-longterm'),('eq-j005','t-market'),
('eq-j006','t-value'),('eq-j007','t-value'),('eq-j008','t-market'),('eq-j009','t-market'),('eq-j010','t-value'),
('eq-j011','t-market'),('eq-j012','t-value'),('eq-j013','t-market'),('eq-j014','t-market'),('eq-j015','t-value'),
('eq-j016','t-value'),('eq-j017','t-market'),('eq-j018','t-market'),('eq-j019','t-market'),('eq-j020','t-market'),
('eq-j021','t-value'),('eq-j022','t-value'),('eq-j023','t-value'),('eq-j024','t-longterm'),('eq-j025','t-market'),
('eq-j026','t-market'),('eq-j027','t-market'),('eq-j028','t-market'),('eq-j029','t-value'),('eq-j030','t-longterm'),
('eq-j031','t-longterm'),('eq-j032','t-value'),('eq-j033','t-market'),('eq-j034','t-value'),('eq-j035','t-value'),
('eq-j036','t-value'),('eq-j037','t-market'),('eq-j038','t-value'),('eq-j039','t-value'),('eq-j040','t-mindset'),
('eq-j041','t-market'),('eq-j042','t-market'),('eq-j043','t-value'),('eq-j044','t-value'),('eq-j045','t-market'),
('eq-j046','t-value'),('eq-j047','t-value'),('eq-j048','t-value'),('eq-j049','t-market'),('eq-j050','t-value');

-- ============================================
-- 菲利普·费雪名言
-- ============================================

INSERT OR IGNORE INTO quotes (id, content_cn, content_en, master_id, source, source_year, is_featured) VALUES
('eq-f001', '投资于那些有突出管理层和独特竞争优势的公司。', 'Invest in companies with outstanding management and unique competitive advantages.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f002', '对公司管理层的深入了解是成功投资的关键。', 'Deep understanding of company management is the key to successful investing.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f003', '长期来看，最成功的投资是那些有持续竞争优势的公司。', 'In the long run, the most successful investments are those in companies with sustainable competitive advantages.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f004', '了解一家公司最好的方式是和它的竞争对手聊聊。', 'The best way to understand a company is to talk to its competitors.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f005', '寻找那些有强大销售组织的公司。', 'Look for companies with strong sales organizations.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f006', '公司的技术优势是保持竞争优势的关键。', 'A companys technological advantage is the key to maintaining competitive advantage.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f007', '管理层必须有长期视角，不能只关注短期利润。', 'Management must have a long-term perspective, not just focus on short-term profits.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f008', '公司的利润率是评估其竞争力的重要指标。', 'A companys profit margin is an important indicator of its competitiveness.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f009', '寻找那些有定价权的公司。', 'Look for companies with pricing power.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f010', '公司的研发投入是未来增长的保证。', 'Company R&D investment is the guarantee of future growth.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f011', '不要只看财务数据，要了解公司的业务模式。', 'Do not just look at financial data; understand the companys business model.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f012', '投资于那些有良好企业文化和管理团队的公司。', 'Invest in companies with good corporate culture and management teams.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f013', '公司的护城河来自于技术、品牌或规模经济。', 'A companys moat comes from technology, brand, or economies of scale.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f014', '深入研究比广泛浏览更能发现好的投资机会。', 'In-depth research finds better investment opportunities than broad browsing.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f015', '选择那些在一个领域做到极致的公司。', 'Choose companies that excel in one field.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f016', '管理层的诚信和能力是选择公司的首要标准。', 'Management integrity and ability are the primary criteria for choosing companies.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f017', '寻找那些有持续创新能力的企业。', 'Look for companies with continuous innovation capability.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f018', '了解公司的成本结构是评估竞争力的重要部分。', 'Understanding a companys cost structure is an important part of assessing competitiveness.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f019', '公司的行业地位决定了其长期盈利能力。', 'A companys industry position determines its long-term profitability.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f020', '投资于那些有长期竞争优势的公司，而不是追逐短期增长。', 'Invest in companies with long-term competitive advantages, not chasing short-term growth.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f021', '管理层的资本配置能力是企业成功的关键。', 'Management capital allocation capability is the key to business success.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f022', '寻找那些能够从行业增长中受益的公司。', 'Look for companies that can benefit from industry growth.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f023', '公司的客户忠诚度是竞争优势的体现。', 'Customer loyalty is an embodiment of competitive advantage.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f024', '了解管理层如何对待员工可以反映公司的文化。', 'Understanding how management treats employees can reflect the companys culture.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f025', '寻找那些有稳定现金流的公司。', 'Look for companies with stable cash flows.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f026', '公司的治理结构影响其长期发展。', 'Corporate governance structure affects its long-term development.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f027', '投资于那些专注于核心业务的公司。', 'Invest in companies that focus on their core business.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f028', '了解公司如何应对竞争挑战是评估其价值的重要方式。', 'Understanding how a company responds to competitive challenges is an important way to assess its value.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f029', '公司的品牌价值是其护城河的重要组成部分。', 'Brand value is an important part of a companys moat.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f030', '寻找那些有高度客户粘性的企业。', 'Look for companies with high customer stickiness.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f031', '管理层的激励机制应该与股东利益一致。', 'Management incentive mechanisms should align with shareholder interests.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f032', '公司的市场份额增长是其竞争力的体现。', 'Growth in market share is an embodiment of competitiveness.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f033', '投资于那些有明确战略的公司。', 'Invest in companies with clear strategies.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f034', '了解公司的供应链管理可以评估其运营效率。', 'Understanding a companys supply chain management can assess its operational efficiency.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f035', '寻找那些有强大分销网络的公司。', 'Look for companies with strong distribution networks.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f036', '公司的研发效率比研发投入更重要。', 'R&D efficiency is more important than R&D spending.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f037', '投资于那些能够适应变化的组织。', 'Invest in organizations that can adapt to change.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f038', '了解公司的资本开支计划可以预测其未来增长。', 'Understanding a companys capital expenditure plans can predict its future growth.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f039', '寻找那些有持续盈利能力的企业。', 'Look for companies with sustainable profitability.', 'm-fisher', '怎样选择成长股', 1958, 0),
('eq-f040', '公司的竞争优势必须难以复制。', 'A companys competitive advantage must be difficult to replicate.', 'm-fisher', '怎样选择成长股', 1958, 0);

-- 标签关联
INSERT OR IGNORE INTO quote_tags (quote_id, tag_id) VALUES
('eq-f001','t-business'),('eq-f002','t-business'),('eq-f003','t-business'),('eq-f004','t-learning'),('eq-f005','t-business'),
('eq-f006','t-business'),('eq-f007','t-business'),('eq-f008','t-business'),('eq-f009','t-business'),('eq-f010','t-business'),
('eq-f011','t-business'),('eq-f012','t-business'),('eq-f013','t-business'),('eq-f014','t-learning'),('eq-f015','t-business'),
('eq-f016','t-business'),('eq-f017','t-business'),('eq-f018','t-business'),('eq-f019','t-business'),('eq-f020','t-business'),
('eq-f021','t-business'),('eq-f022','t-business'),('eq-f023','t-business'),('eq-f024','t-business'),('eq-f025','t-business'),
('eq-f026','t-business'),('eq-f027','t-business'),('eq-f028','t-business'),('eq-f029','t-business'),('eq-f030','t-business'),
('eq-f031','t-business'),('eq-f032','t-business'),('eq-f033','t-business'),('eq-f034','t-business'),('eq-f035','t-business'),
('eq-f036','t-business'),('eq-f037','t-business'),('eq-f038','t-business'),('eq-f039','t-business'),('eq-f040','t-business');

-- ============================================
-- 杰西·利弗莫尔名言
-- ============================================

INSERT OR IGNORE INTO quotes (id, content_cn, content_en, master_id, source, source_year, is_featured) VALUES
('eq-v001', '市场永远不会错，只有市场参与者的看法会错。', 'The market is never wrong; only market participants views can be wrong.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v002', '赚大钱不是靠交易技巧，而是靠坐着不动。', 'Making big money is not about trading skill, but about sitting still.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v003', '在市场确认趋势之前，不要急于行动。', 'Before the market confirms the trend, do not rush to act.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v004', '我的亏损教会了我很多东西。', 'My losses have taught me a lot.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v005', '永远不要在错误的时候加仓。', 'Never add to a losing position.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v006', '时机就是一切。', 'Timing is everything.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v007', '在市场开始上涨之前，价格已经在底部徘徊很久了。', 'Before the market starts rising, prices have been hovering at the bottom for a long time.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v008', '不要试图猜测市场将要做什么，而是等待市场告诉你。', 'Do not try to guess what the market will do; wait for the market to tell you.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v009', '耐心等待是交易中最重要的品质。', 'Patience is the most important quality in trading.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v010', '在股票市场上，没有人能赢过所有的人。', 'In the stock market, no one can beat everyone.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v011', '跟随趋势交易，直到趋势反转。', 'Follow the trend until the trend reverses.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v012', '亏损的原因往往是过早地买入或卖出。', 'The cause of losses is often buying or selling too early.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v013', '在市场确认方向之前保持观望。', 'Stay on the sidelines until the market confirms direction.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v014', '成功交易的秘诀是知道什么时候退出。', 'The secret to successful trading is knowing when to exit.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v015', '不要听别人的建议，坚持自己的判断。', 'Do not listen to others advice; stick to your own judgment.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v016', '在交易中，最重要的不是买什么，而是什么时候买。', 'In trading, the most important thing is not what to buy, but when to buy.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v017', '学会亏钱和学会赚钱一样重要。', 'Learning to lose money is as important as learning to make money.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v018', '在交易中，情绪是最大的敌人。', 'In trading, emotions are the biggest enemy.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v019', '不要试图抄底或逃顶。', 'Do not try to pick bottoms or tops.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v020', '市场的行为是由人性决定的。', 'Market behavior is determined by human nature.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v021', '永远不要逆势交易。', 'Never trade against the trend.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v022', '在交易中，资金管理是最重要的。', 'In trading, money management is the most important.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v023', '当你亏损时，减少交易量。', 'When you are losing, reduce trading volume.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v024', '在市场证明你正确之前，不要加仓。', 'Do not add to a position until the market proves you right.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v025', '交易的艺术在于知道什么时候持有，什么时候卖出。', 'The art of trading is knowing when to hold and when to sell.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v026', '在投机市场，没有什么是确定的。', 'In the speculative market, nothing is certain.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v027', '在市场恐慌时买入，在市场兴奋时卖出。', 'Buy when the market panics, sell when the market is excited.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v028', '成功的交易者知道什么时候应该休息。', 'Successful traders know when they should take a break.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v029', '不要爱上你的头寸。', 'Do not fall in love with your positions.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v030', '交易记录是最好的老师。', 'Trading records are the best teachers.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v031', '在交易中，止损是最重要的纪律。', 'In trading, stop-loss is the most important discipline.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v032', '市场趋势一旦形成，往往会持续一段时间。', 'Once a market trend forms, it tends to continue for some time.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v033', '不要因为股价低就买入。', 'Do not buy just because the stock price is low.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v034', '成功的交易需要耐心、勇气和纪律。', 'Successful trading requires patience, courage, and discipline.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v035', '在交易中，不要追求完美，而是追求一致。', 'In trading, do not pursue perfection, pursue consistency.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v036', '市场的记忆是短暂的，机会会不断重复。', 'The markets memory is short; opportunities keep repeating.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v037', '不要把运气当作技能。', 'Do not mistake luck for skill.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v038', '在交易中，最重要的不是你的看法对不对，而是你错了怎么办。', 'In trading, the most important thing is not whether your view is right, but what you do when you are wrong.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v039', '学会在错误中生存是成功交易的关键。', 'Learning to survive mistakes is the key to successful trading.', 'm-livermore', '股票大作手回忆录', 1923, 0),
('eq-v040', '市场的波动创造了盈利的机会。', 'Market volatility creates profit opportunities.', 'm-livermore', '股票大作手回忆录', 1923, 0);

-- 标签关联
INSERT OR IGNORE INTO quote_tags (quote_id, tag_id) VALUES
('eq-v001','t-market'),('eq-v002','t-longterm'),('eq-v003','t-market'),('eq-v004','t-learning'),('eq-v005','t-risk'),
('eq-v006','t-market'),('eq-v007','t-market'),('eq-v008','t-market'),('eq-v009','t-mindset'),('eq-v010','t-market'),
('eq-v011','t-market'),('eq-v012','t-market'),('eq-v013','t-market'),('eq-v014','t-risk'),('eq-v015','t-mindset'),
('eq-v016','t-market'),('eq-v017','t-learning'),('eq-v018','t-mindset'),('eq-v019','t-market'),('eq-v020','t-market'),
('eq-v021','t-market'),('eq-v022','t-risk'),('eq-v023','t-risk'),('eq-v024','t-risk'),('eq-v025','t-market'),
('eq-v026','t-market'),('eq-v027','t-contrarian'),('eq-v028','t-mindset'),('eq-v029','t-mindset'),('eq-v030','t-learning'),
('eq-v031','t-risk'),('eq-v032','t-market'),('eq-v033','t-value'),('eq-v034','t-mindset'),('eq-v035','t-mindset'),
('eq-v036','t-market'),('eq-v037','t-mindset'),('eq-v038','t-risk'),('eq-v039','t-risk'),('eq-v040','t-market');
